void initializer();
void registerAdmin();
void login();
void makeFilesandFolders();
void loginPannel();
void menu();
void addUser();
int checkUserStatus(std::string);
void encrypt(std::string *);
void decrypt(std::string *);
void removeUser();
void viewUser(int n, int q);
void addMovie();
void removeMovie();
void viewMovie(int n, int q);
void rentMovie();
void getIMDBRequestID(std::string &userRequestedImdb);
void returnMovie();