#include <iostream>
#include <iostream>
#include <string>
#include <fstream>
#include <ios>
#include <windows.h>
#include <conio.h>
#include <bits/stdc++.h>
#include <direct.h>
#include <ctime>
#include "encdec.h"
#include "functions.h"
#include "objects.h"
#include "screen.h"
#include "initializer.h"
#include "registerAdmin.h"
#include "makeFandF.h"
#include "loginPannel.h"
#include "menuPannel.h"
#include "addAUser.h"
#include "removeAUser.h"
#include "viewAllUsers.h"
#include "addAMovie.h"
#include "removeAMovie.h"
#include "viewAllMovie.h"
#include "extraFunctions.h"
#include "rentAMovie.h"
#include "returnAMovie.h"
#include "viewRentedMovies.h"